/*
===============================================================================================================================================
5. MAGNITUDE ANALYSIS 
===============================================================================================================================================
SCRIPT PURPOSE
		This script perform magnitude analysis:

      -Which compares the measure of value by catgories. it help us understand the importance of different categories
      -It is the summation of measure by dimension
USAGE NOTES
	  - Run the script to the summation of measure by dimension e.g Totalsales by Country
    - Aggregate function like SUM(), AVG(), COUNT() are used to query the level of aggregation with GROUP BY to categorize the measure. e.g
    - Find total customers by countries
    - Find total customrs by gender
    - Find total products by category
    - What is the average costs in each category?
    - What is the total revenue generated for each category?
    - Find total revenue is generated by each customer
    - What is the distribution of sold items aross countries?
===============================================================================================================================================

*/

----Find total customers by countries
SELECT country,
COUNT(customer_key) AS total_customer
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customer DESC

---Find total customrs by gender
SELECT gender,
Count(customer_key) AS total_customer
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customer DESC

---Find total products by category
SELECT category,
COUNT(product_key) AS total_product
FROM gold.dim_products
GROUP BY category
ORDER BY total_product DESC

---What is the average costs in each category?
SELECT Category,
AVG(cost) AS Average_cost
FROM gold.dim_products
GROUP BY category
ORDER BY Average_cost DESC

---What is the total revenue generated for each category?
SELECT 
p.Category,
SUM(s.sales_amount) AS Total_revenue
FROM gold.fact_sales s
LEFT JOIN
gold.dim_products p
ON s.product_key = p.product_key
GROUP BY category
ORDER BY Total_revenue DESC

---Find total revenue is generated by each customer
SELECT 
c.customer_key,c.first_name,c.last_name,
SUM(s.sales_amount) AS Total_revenue
FROM gold.fact_sales s
LEFT JOIN
gold.dim_customers c
ON s.customer_key = c.customer_key
GROUP BY c.customer_key,c.first_name,c.last_name
ORDER BY Total_revenue DESC

--- What is the distribution of sold items aross countries?
SELECT 
c.country,
SUM(s.quantity) AS 'total sold items'
FROM gold.fact_sales s
LEFT JOIN
gold.dim_customers c
ON s.customer_key = c.customer_key
GROUP BY c.country
ORDER BY 'total sold items' DESC
